---
- hosts: dev
  become: True
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Python pip
      apt:
        name: python3-pip
        state: present
    - name: Install Docker
      apt:
        name: docker-ce
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: vishalapp
        image: "vishalsaxena29/vishalapp:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
